version: '3.8'
services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cicd_notifier_staging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password_123
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres-test:
        condition: service_healthy
    ports:
      - "8083:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:test_password_123@postgres-test:5432/cicd_notifier_staging?sslmode=disable
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      backend-test:
        condition: service_healthy
    ports:
      - "3003:80"
    environment:
      REACT_APP_API_URL: http://localhost:8083

volumes:
  postgres_test_data:
