version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: cicd-notifier-postgres-dev
    environment:
      POSTGRES_DB: cicd_notifier_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/scripts/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cicd_notifier_dev"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_dev_data:
