version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cicd_postgres
    environment:
      POSTGRES_DB: cicd_notifier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jQlwjVKoQw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - TELEGRAM_BOT_TOKEN=your-telegram-bot-token
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: