version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - TELEGRAM_TOKEN=your-telegram-bot-token
    command: air -c .air.toml